name:                streamly-zip
version:             0.0.1
github:              "shlok/streamly-zip"
license:             BSD3
author:              "Shlok Datye"
maintainer:          "sd-haskell@quant.is"
copyright:           "2022 Shlok Datye"

synopsis:            Stream data from zip and zip64 archives using the streamly library.
category:            Archive, Codec, Streaming, Streamly

description:         Please see the README on GitHub at <https://github.com/shlok/streamly-zip#readme>

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- test/data/data.zip

extra-libraries:
- zip

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.11
- containers >= 0.6 && < 0.7
- streamly >= 0.8 && < 0.9

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  streamly-zip-test:
    main:                TestSuite.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base16-bytestring >= 1.0.1.0 && < 1.1
    - cryptohash >= 0.11.9 && < 0.12
    - directory >= 1.3.6.0 && < 1.4
    - filepath >= 1.4.2.1 && < 1.5
    - QuickCheck >= 2.13.2 && < 2.15
    - streamly-zip
    - tar >= 0.5.1.1 && < 0.6
    - tasty >= 1.2.3 && < 1.5
    - tasty-hunit >= 0.10.0.2 && < 0.11
    - tasty-quickcheck >= 0.10.1.1 && < 0.11
    - temporary >= 1.3 && < 1.4
    - zlib >= 0.6.2.1 && < 0.7
